spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL:jdbc:mysql://localhost:3306/snapbuy_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    open-in-view: false

    defer-datasource-initialization: true

    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: never

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 60000

  mail:
    host: smtp.gmail.com
    port: 587

    username: ${MAIL_USERNAME:john.doe@gmail.com}
    password: ${MAIL_PASSWORD:abcd efgh ijkl mnop}

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:

  jwt:
    secret: ${JWT_SECRET:0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789}

  razorpay:
    key-id: ${RAZORPAY_KEY_ID:rzp_test_1234567890abcd}
    key-secret: ${RAZORPAY_KEY_SECRET:1234567890abcdefghijklmnopqrstuvwxyz}

  cloudinary:
    cloud-name: ${CLOUDINARY_CLOUD_NAME:my-cloud-name}
    api-key: ${CLOUDINARY_API_KEY:123456789012345}
    api-secret: ${CLOUDINARY_API_SECRET:abcdefghijklmnopqrstuvwxyz123456}

  brevo:
    api-key: ${BREVO_API_KEY}
    sender-email: ${BREVO_SENDER_EMAIL}
    sender-name: SnapBuy
  cors:
    allowed-origins:
      - ${FRONTEND_URL:http://localhost:5173}

logging:
  level:
    root: INFO
    com.snapBuy: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE